EDITOR=${EDITOR:-/usr/bin/micro}
VISUAL=${VISUAL:-/usr/bin/zeditor}
PAGER=${PAGER:-/usr/bin/less -R}
SUDO_EDITOR=${SUDO_EDITOR:-$EDITOR}
DIFFPROG=${EDITOR:-/usr/bin/micro}
TERMINAL=${TERMINAL:-/usr/bin/xdg-terminal-exec}
