[packages_void]
packages = [
  "accountsservice",
  "adw-gtk-theme",
  "alsa-pipewire",
  "ark",
  "aubio",
  "awww",
  "bat",
  "bluez",
  "bluez-deprecated",
  "blueman",
  "breeze",
  "breeze-qt5",
  "brightnessctl",
  "btop",
  "cava",
  "chafa",
  "chezmoi",
  "chromium-widevine",
  "cliphist",
  "curl",
  "dbus",
  "ddcutil",
  "dinit",
  "elogind",
  "eza",
  "fastfetch",
  "fd",
  "ffmpegthumbs",
  "figlet",
  "fish-shell",
  "flatpak",
  "font-inter",
  "fonts-roboto-ttf",
  "fzf",
  "git",
  "github-cli",
  "gnome-keyring",
  "greetd",
  "gsettings-desktop-schemas",
  "gstreamer1-pipewire",
  "gtk+3",
  "gtk4",
  "gtk4-layer-shell",
  "gpu-screen-recorder",
  "gvfs",
  "gvfs-mtp",
  "handy-bin",
  "helium-browser",
  "i2c-tools",
  "ImageMagick",
  "inotify-tools",
  "jq",
  "kcharselect",
  "kde-cli-tools",
  "kf6-frameworkintegration",
  "kitty",
  "lazygit",
  "libadwaita",
  "libjack-pipewire",
  "libnotify",
  "libpulseaudio",
  "libvirt",
  "man-db",
  "man-pages",
  "matugen",
  "mesa-dri",
  "mesa-vaapi",
  "mesa-vulkan-lavapipe",
  "mise",
  "nautilus",
  "neovim",
  "nerd-fonts-otf",
  "nerd-fonts-ttf",
  "network-manager-applet",
  "NetworkManager",
  "niri",
  "nix",
  "noctalia",
  "noto-fonts-emoji",
  "octoxbps",
  "pamixer",
  "papirus-icon-theme",
  "papirus-folders",
  "parallel",
  "pavucontrol-qt",
  "pipewire",
  "playerctl",
  "polkit",
  "polkit-kde-agent",
  "qemu",
  "qt5-graphicaleffects",
  "qt5-imageformats",
  "qt5-quickcontrols",
  "qt5-quickcontrols2",
  "qt5-wayland",
  "qt6-imageformats",
  "qt6-wayland",
  "qt6ct",
  "ristretto",
  "rsync",
  "rustdesk",
  "sheldon",
  "socklog-void",
  "starship",
  "tree",
  "tuigreet",
  "udiskie",
  "unzip",
  "uv",
  "vim",
  "virt-manager",
  "virt-viewer",
  "viu",
  "vscode",
  "vsv",
  "Vulkan-Tools",
  "wget",
  "wireplumber",
  "wl-clip-persist",
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-wlr",
  "xdg-user-dirs",
  "xsettingsd",
  "xtools",
  "xwayland-satellite",
  "yazi",
  "zathura",
  "zed",
  "zoxide",
  "zsh"
]
