[preferred]
default=umbriel;gtk
org.freedesktop.impl.portal.ScreenCast=umbriel
org.freedesktop.impl.portal.Screenshot=umbriel
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Secret=gnome-keyring
