# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
format = '$directory$all$character'
right_format = '$time'

[character]
success_symbol = '[●](bold green)'
error_symbol = '[●](bold red)'

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"
symbol = ""
disabled = false

[line_break]
disabled = true

[git_status]
disabled = true

[time]
disabled = false
format = '[$time]($style) '
style = 'bright-black'

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow) '

[rust]
format = '[$symbol($version )]($style)'
disabled = false

[package]
disabled = false
format = '[$symbol$version]($style) '

[directory]
truncation_length = 3
truncate_to_repo = true
use_logical_path = true
